# -*- coding: utf-8 -*-
"""multiclassLogReg.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a3qwvDCJs8hHOJiruKHTyo8Hl_EWoM5H

# Multi-Class Regression **Functions**
"""

def soft_max(X,Y,B):
    
    numExamples, numFeatures = X.shape
    numExamples, numClasses = Y.shape
    
    numerator = np.exp(X@B)
    denom = np.sum(numerator,axis =1) 
    denom = np.reshape(denom,(numExamples,1))  
    denom = np.tile(denom,(1,numClasses)) 
    p = numerator/denom
    
    return p
  
  

def eval_f(X,Y,B):
  f = np.sum(Y*np.log(soft_max(X,Y,B)))

  return -f

def eval_grad(X,Y,B):
    
    
    numExamples, numFeatures = X.shape
    numExamples, numClasses = Y.shape
    grad = np.zeros((numFeatures,numClasses))
    
    grad = X.T@(soft_max(X,Y,B) - Y)
    
    
    return grad